tests/pkg_fatfs: fix sprintf format overflow warning
Some platforms issue this:

    tests/pkg_fatfs/main.c: In function '_mkfs':
    tests/pkg_fatfs/main.c:355:26: error: '%d' directive writing between 1 and 11 bytes into a region of size 8 [-Werror=format-overflo
    w=]
      355 |     sprintf(volume_str, "%d:/", vol_idx);
          |                          ^~
    tests/pkg_fatfs/main.c:355:25: note: directive argument in the range [-2147483648, 0]
      355 |     sprintf(volume_str, "%d:/", vol_idx);
          |                         ^~~~~~
    tests/pkg_fatfs/main.c:355:5: note: 'sprintf' output between 4 and 14 bytes into a destination of size 8
      355 |     sprintf(volume_str, "%d:/", vol_idx);
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors

The cause is vol_idx being converted by atoi(), so it might be negative.
This commit increases the stack array so it cannot overflow.